ZbaseURL = "http://miraglobal.com/seazine/"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en-us"
pygmentsCodefences = true
pygmentsUseClasses = true
rssLimit = 10
theme = "hermit"
title = "SeaZINE"
[author]
name = "Manuela de los Rios"
[blackfriday]
[[menu.main]]
name = "Manuela"
url = "www.linkedin.com/in/manueladelosrios"
weight = 2
[[menu.main]]
name = "About"
url = "about-hugo/"
weight = 1
[params]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
dateformShort = "Jan 2"
footerCopyright = " &#183; <a href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY-NC 4.0</a>"
homeSubtitle = "The revolution at sea"
justifyContent = false
themeColor = "#494f5c"
[[params.social]]
name = "twitter"
url = "https://twitter.com/Manuela_de_rios"
[[params.social]]
name = "instagram"
url = "https://instagram.com/"
[[params.social]]
name = "facebook"
url = "https://facebook.com/"
[taxonomies]
tag = "tags"
